version: 2.1

orbs:
  azure-acr: circleci/azure-acr@dev:alpha
  orb-tools: circleci/orb-tools@9.0

# Pipeline parameters
parameters:
  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
  # job, by default.
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

workflows:
  lint_pack-validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires: [orb-tools/lint]

      - orb-tools/publish-dev:
          orb-name: circleci/azure-acr
          context: orb-publisher
          requires: [orb-tools/pack]

      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publisher
          requires: [orb-tools/publish-dev]

  integration-tests_prod-release:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - azure-acr/build-and-push-image:
          name: build-and-push
          context: orb-publishing
          registry-name: azureacrorb
          login-server-name: azureacrorb.azurecr.io
          dockerfile: test.Dockerfile
          path: test
          repo: azure-acr-orb
          tag: $CIRCLE_TAG

      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: circleci/azure-acr
          context: orb-publisher
          add-pr-comment: true
          bot-token-variable: GHI_TOKEN
          bot-user: orb-publisher
          ssh-fingerprints: 00:4d:7e:d7:f8:60:f9:5c:8c:6a:5d:89:49:40:a6:97
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - build-and-push
          filters:
            branches:
              only: master
