version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.3.0
  azure-acr: {}

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  integration-test:
    docker:
      - image: cimg/base:current
    steps:
      - run: echo "Placeholder for integration tests while we wait for Azure infrastructure."

workflows:
  test-deploy:
    jobs:
      - azure-acr/build-and-push-image:
          name: build-and-push
          context: azure-acr-orb
          registry-name: azureacrorb
          login-server-name: azureacrorb.azurecr.io
          dockerfile: test.Dockerfile
          path: test
          repo: azure-acr-orb
          tag: $CIRCLE_TAG
          filters: *filters
      - integration-test:
          filters: *filters
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: circleci/azure-acr
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
          context: azure-acr-orb
          filters: *release-filters
