version: 2.1
orbs:
  azure-acr: circleci/azure-acr@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

workflows:
  test-deploy:
    jobs:
      - azure-acr/build-and-push-image:
          name: build-and-push
          context: orb-publishing
          registry-name: azureacrorb
          login-server-name: azureacrorb.azurecr.io
          dockerfile: test.Dockerfile
          path: test
          repo: azure-acr-orb
          tag: $CIRCLE_TAG
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: circleci/azure-acr
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - build-and-push
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/